scoutapp/scout-apm-php

- src/Config/Source/DerivedSource.php
Mirror of https://github.com/scoutapp/scout_apm_python/pull/240 for this library. The core agent has used the default socket name `scout-agent.sock` when started solo since version 1.0.0, so match it.
> Update default socket path

- composer.json
Some users have 3.x required in their Laravel apps, and both 2.x and 3.x work fine. There's little to no chance of backwards incompatible changes in this library because it's meant to polyfill a single, defined-elsewhere function. Even the 2.x to 3.x was just dropping support for very old PHPs.
> Loosen version requirement for ralouphie/getallheaders

- composer.json
- composer.lock
- src/Events/Metadata.php
- tests/Unit/Events/MetadataTest.php
Adds `libraries` and `git_sha` into the metadata.
> Include libraries and git_sha in metadata from ocramius/package-versions

- composer.json
- composer.lock
- phpunit.xml.dist
- src/Agent.php
- src/ScoutApmAgent.php
- tests/Unit/ConfigTest.php
Resolves a `@todo` comment I had - we need an interface for stability and public consumption (and also is a requirement for mocking in `scout-apm-laravel`).
> Interface for agent

- src/Config/Source/DefaultSource.php
- src/CoreAgent/Downloader.php
Unfortunately, the version `latest` actually resolves to a CoreAgent from
several versions ago. I'll be fixing that separately.
All of the other language agents lock to an exact version anyway, so that's a
better choice for this one as well.
> Lock CoreAgent to 1.2.1

- CHANGELOG.md
- src/Agent.php
- src/Config/ConfigKey.php
- src/Config/Source/DefaultSource.php
- src/CoreAgent/Downloader.php
- src/Events/Metadata.php
- tests/Unit/AgentTest.php
- tests/Unit/Events/MetadataTest.php
Fixes #59 
Fixes #70 
Fixes #65 
Fixes #60 
Fixes #87 
Fixes #73
> Detect application root, add some configurations

- CHANGELOG.md
- src/Agent.php
- src/Events/Request/Request.php
- src/Events/Span/Span.php
- src/Events/Tag/Tag.php
- tests/Integration/AgentTest.php
- tests/Unit/Events/Span/SpanTest.php
> Suppress backtraces for Controller/Middleware/Job spans

- CHANGELOG.md
- src/Config/Source/DefaultSource.php
A few bug fixes, but most notable fix is better parsing/naming of SQL
emitted in real-life by Laravel. So instead of having "SQL" as the name
of the row in the web UI, it will say "User/Select" or "Post/Update" and
so on more often.
Note: it wasn't skipping any instrumented SQL previously, just was
falling back to a generic name for it.
> Updates CoreAgent to 1.2.4

- CHANGELOG.md
- README.md
- src/Agent.php
- src/Connector/Connector.php
- src/Connector/SocketConnector.php
- src/CoreAgent/AutomaticDownloadAndLaunchManager.php
- src/CoreAgent/Downloader.php
- src/CoreAgent/Manifest.php
- src/Events/Request/Request.php
- src/Events/Span/Span.php
- src/Helper/RecursivelyCountSpans.php
- tests/Integration/MessageCapturingConnectorDelegator.php
- tests/Unit/AgentTest.php
- tests/Unit/Events/Request/RequestTest.php
- tests/Unit/Events/Span/SpanTest.php
- tests/Unit/Helper/RecursivelyCountSpansTest.php
- Hardens `Agent` API to require Logger in `::fromConfig()`
- Removes deprecated API (`Agent::fromDefaults()`)
- Makes `Agent::__construct` into a `private` method (forces using `::fromConfig()`)
- Return the data that was read from the socket in `Connector` (for logging, primarily)
- Adds a bunch of extra logging everywhere
- Adds docs on how to turn off all the logging
> Improvements to API and logging/debugging

- phpunit.xml.dist
- src/Connector/SocketConnector.php
Didn't notice this before because phpunit swallows warnings etc. and converts them to exceptions, which of course get caught by the `catch` and operates as expected. However, outside of phpunit, these warnings were bubbling up.
> Fix warning on failed socket_connect

- src/Config/Source/DefaultSource.php
(from CA's changelog)
[1.2.6] 2019-12-03
Fixed:
* Use SQL derived names in SpanTraces (#97)
[1.2.5] 2019-12-02
Added:
* Autoclose running spans when request finishes (#93)
* Rate Limit AppServerLoad metadata (#94)
* Add `language_version` key to AppServerLoad metadata (#95)
Fixed:
* Prevent errors if AppServerLoad metadata is not set (#92)
> Update CoreAgent version to 1.2.6, with several bug fixes:

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
- src/Agent.php
- src/Cache/DevNullCache.php
- tests/Integration/AgentTest.php
- tests/Unit/Cache/DevNullCacheTest.php
Fixes #100
Note: BC break here is the addition of the `Cache` parameter - it's `null`able and unlikely to affect anyone unless they implemented a custom `Connector` (unlikely)
> Send metadata less often

- README.md
The native extension exposes a bug further down the agent stack that causes missing data. Removing the recommendation to install it for now, and will readd when the bug is fixed.
> Temporarily remove instructions for Native Ext

- .travis.yml
Since we support it in `composer.json` (`"php": ">=7.1.0,<7.5.0",`) we should probably have this in our build...
> Added PHP 7.4 support to CI build

- src/CoreAgent/Downloader.php
- src/CoreAgent/Manifest.php
> Correctly handle warnings when reading manifest and cleaning download locks

- src/Agent.php
- tests/Unit/AgentTest.php
If we catch all exceptions raised whilst gathering/sending metadata, we can log it and continue to send the actual request. Exceptions should not be bubbling up, especially for something trivial.
> Catch exceptions raised whilst sending metadata

- src/Events/Metadata.php
- tests/Unit/Events/MetadataTest.php
> Default SCM subdirectory to null

- src/Agent.php
- src/Events/Tag/Tag.php
- src/Extension/RecordedCall.php
- tests/Integration/AgentTest.php
From PHP internal function calls recorded by the extension, only tag the arguments if there are any interesting arguments to be tagged.
> Only tag args if there are any

- src/Connector/SocketConnector.php
- tests/Unit/Connector/SocketConnectorTest.php
Fixes #138 
Turns out, actually the errors raised with `socket_read`/`socket_send` calls are already correctly handled with `socket_last_error`, so we just need to suppress the errors from bubbling up with the `@` operator. Testing this class is going to be very tricky however, but we can delay that for #64 as a future improvement I think.
> Wrap socket calls with error handler

- CHANGELOG.md
- src/Agent.php
- src/ScoutApmAgent.php
- tests/Unit/AgentTest.php
Needed to implement scoutapp/scout-apm-laravel#35 properly.
> Expose new ScoutApmAgent endpoint to start a new request

- src/Events/Request/Request.php
- src/Events/Tag/Tag.php
- src/Helper/FetchRequestHeaders.php
- src/Helper/Timer.php
- tests/Unit/Events/Request/RequestTest.php
- tests/Unit/Helper/FetchRequestHeadersTest.php
- tests/Unit/Helper/TimerTest.php
> Capture request queue time

- .gitignore
- Makefile
- src/Agent.php
- tests/Unit/AgentTest.php
> Improve test coverage for Agent

- src/Agent.php
- src/Config.php
- src/Config/ConfigKey.php
- src/ScoutApmAgent.php
- tests/Unit/AgentTest.php
https://github.com/scoutapp/scout-apm-laravel/pull/44#issuecomment-571707936
Updating this in `scout-apm-php` since it is common functionality needed in all agents.
> Added ability to disable instrumentation by name

- .travis.yml
- src/Agent.php
- src/Connector/Command.php
- src/Events/Metadata.php
- src/Events/RegisterMessage.php
- src/Events/Request/Request.php
- src/Events/Span/Span.php
- src/Events/Tag/Tag.php
- tests/Integration/AgentTest.php
- tests/Integration/MessageCapturingConnectorDelegator.php
- tests/check-memory-leaks.sh
- tests/isolated-memory-test.php
Fixes #157 
We use a tree that references itself several places (such as `$parent` and `$children` all over), I think there were "dangling" references left lying around. I've added a `cleanUp` method to any `Command` which basically unsets all its own properties. This seems to have brought down the memory usage significantly after looping. I'm not 100% convinced this fixes everything, and I haven't yet been able to understand why this is necessary at all, so I'd like to get some further insight, perhaps we can come up with a better way to fix this.
> Fix memory leaking from cyclic references

- src/Agent.php
- src/Events/Request/Request.php
- src/Helper/Timer.php
- tests/Integration/AgentTest.php
- tests/Unit/Events/Request/RequestTest.php
> Fix queue time calculation

- CHANGELOG.md
- src/Config/Source/DefaultSource.php
Now that core-agent 1.2.8 is released, this change sets the default version
downloaded to be the latest 1.2.8 release.﻿
> Use core-agent 1.2.8

- .github/workflows/build.yml
- CHANGELOG.md
- phpunit.xml.dist
- tests/Integration/AgentTest.php
- tests/Integration/CheckScoutApmKeyListener.php
- tests/isolated-memory-test.php
Since some tests use a special environment variable `SCOUT_APM_KEY` (named differently on purpose), we need to import this as a "secret" key (see https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets ).
This needs to be added by @cschneid in the settings before it'll work however...﻿
(relates to #177)
> Fix missing env in CI

- src/Agent.php
- src/Config/Source/DefaultSource.php
- src/Config/Source/DerivedSource.php
- src/Connector/ConnectionAddress.php
- src/Connector/Exception/FailedToConnect.php
- src/Connector/Exception/FailedToSendCommand.php
- src/Connector/Exception/NotConnected.php
- src/Connector/SocketConnector.php
- src/CoreAgent/Launcher.php
- tests/Integration/AgentTest.php
- tests/Unit/AgentTest.php
- tests/Unit/Config/Source/DerivedSourceTest.php
- tests/Unit/Connector/ConnectionAddressTest.php
- tests/Unit/Connector/SocketConnectorTest.php
- tests/Unit/CoreAgent/LauncherTest.php
- tests/check-memory-leaks.sh
Fixes #184
- Added ConnectionAddress value object for TCP/socket path support
- Use ConnectionAddress to determine whether to use TCP or UNIX sockets
- Set default core_agent_socket_path configuration to TCP address 127.0.0.1:6590
> Use a TCP address for core agent communication

- src/Connector/Exception/FailedToSendCommand.php
- src/Connector/SocketConnector.php
> Added additional checking if response length is beyond a reasonable limit (10mb)

- CHANGELOG.md
- composer.json
- composer.lock
- psalm.xml.dist
- src/Agent.php
- src/Connector/Exception/FailedToSendCommand.php
- src/Connector/SocketConnector.php
- src/Events/Request/Request.php
- src/Events/Tag/TagRequest.php
- src/Events/Tag/TagSpan.php
- src/Extension/PotentiallyAvailableExtensionCapabilities.php
- src/Extension/RecordedCall.php
- src/Helper/RecursivelyCountSpans.php
- tests/Integration/AgentTest.php
- tests/Integration/MessageCapturingConnectorDelegator.php
- tests/Integration/TestHelper.php
- tests/Unit/AgentTest.php
- tests/Unit/Connector/Exception/FailedToSendCommandTest.php
- tests/Unit/Events/Request/RequestTest.php
- tests/Unit/Events/Span/SpanTest.php
- tests/Unit/Events/Tag/TagRequestTest.php
- tests/Unit/Events/Tag/TagSpanTest.php
- tests/Unit/Extension/PotentiallyAvailableExtensionCapabilitiesTest.php
- tests/Unit/Extension/RecordedCallTest.php
- tests/Unit/Helper/TimerTest.php
- tests/isolated-memory-test.php
﻿- Added different log level for FailedToSendCommand when response length is too high
- Static analysis fixes for latest Psalm release
Fixes #197
> Adjust log level for Response length limit

- CHANGELOG.md
- src/Events/Span/Span.php
> Remove Span::INSTRUMENT_* constants in favour of SpanReference::INSTRUMENT_* constants

- .github/fixtures/lumen-app.php
- .github/workflows/laravel.yml
- .github/workflows/lumen.yml
- .github/workflows/symfony.yml
- .phpstorm.meta.php
- CHANGELOG.md
- composer.json
- composer.lock
- known-issues.xml
- phpunit.xml.dist
- src/Laravel/Middleware/ActionInstrument.php
- src/Laravel/Providers/ScoutApmServiceProvider.php
- src/Laravel/Router/AutomaticallyDetermineControllerName.php
- src/Laravel/Router/DetermineLaravelControllerName.php
- src/Laravel/Router/DetermineLumenControllerName.php
- tests/Unit/Laravel/Middleware/ActionInstrumentTest.php
- tests/Unit/Laravel/Providers/ScoutApmServiceProviderTest.php
- tests/Unit/Laravel/Providers/ScoutApmServiceProviderTestBase.php
- tests/Unit/Laravel/Providers/ScoutApmServiceProviderUsingLaravelTest.php
- tests/Unit/Laravel/Providers/ScoutApmServiceProviderUsingLumenTest.php
- tests/Unit/Laravel/Router/DetermineLaravelControllerNameTest.php
- tests/Unit/Laravel/Router/DetermineLumenControllerNameTest.php
Fixes scoutapp/scout-apm-laravel#48
This PR adds support for Lumen, targeting `6.1.0` release of `scout-apm-php`.
* :heavy_check_mark: 5.* (5.5+)
* :heavy_check_mark: 6.*
* :heavy_check_mark: 7.*
* :heavy_check_mark: 8.*
> Adds Lumen support

- CHANGELOG.md
- src/Helper/FetchRequestHeaders.php
- tests/Unit/Events/Request/RequestTest.php
- tests/Unit/Helper/FetchRequestHeadersTest.php
Fixes #212 
Previously only `$_SERVER` values prefixed with `HTTP_` (i.e. HTTP headers) were returned; I updated this as in some cases (e.g. with nginx configuration) the `X-Request-Start` header value may be set directly into `$_SERVER`, rather than being prefixed (such as how Apache does by default). This makes the header checking more flexible and less fussy to configure.
> Fix X-Request-Start header when added to server

- CHANGELOG.md
- src/Events/Metadata.php
> Add additional checks to ensure string is returned to avoid type error

- src/Logger/FilteredLogLevelDecorator.php
- tests/Unit/Logger/FilteredLogLevelDecoratorTest.php
Prior to this change, an invalid log level passed to the FilteredLogLevelDecorator
constructor would result in an InvalidArgumentException. This means that a mis-
configured production system could fail to boot.
This patch proposes that an invalid log level should not be a hard failure. The
change logs the invalid log level to the 'realLogger' as an error, then sets the
default log level to 'debug'.
> Log invalid log levels, then default to 'debug'

- CHANGELOG.md
- src/Config.php
- tests/Unit/ConfigTest.php
Mentioned in https://github.com/scoutapp/scout-apm-php/pull/228#issuecomment-878425187 - reminded me that the new `uri_filtered_params` config should be converted from JSON string, if it is not already.
> Ensure uri_filtered_params are coerced from JSON

- .github/workflows/laravel.yml
- .github/workflows/lumen.yml
- CHANGELOG.md
- README.md
- known-issues.xml
- src/Agent.php
- src/Config.php
- src/Events/Request/Request.php
- src/Logger/FilteredLogLevelDecorator.php
- tests/Unit/AgentTest.php
- tests/Unit/Events/Request/RequestTest.php
- tests/Unit/Logger/FilteredLogLevelDecoratorTest.php
- Reduce log level of span limit reached message
- Increased span limit to 3000
- Change default log level back to DEBUG to assist with log visibility
> Adjust log levels

- .github/workflows/laravel.yml
- .github/workflows/lumen.yml
Seems there's sometimes a race condition in which `core-agent` does not fully start up by the time we try the `wget localhost` and check the logs in the E2E tests. This adds a primitive workaround - load the page once to get `core-agent` started, sleep, then run it again for the "actual" check. It's not pretty, but if we still get issues after then there may be something else wrong.
> Allow core-agent to fully start in GH Actions

- .github/workflows/quality.yml
- .github/workflows/roave-backwards-compatibility-check.sh
- composer.json
- composer.lock
- known-issues.xml
- src/Extension/PotentiallyAvailableExtensionCapabilities.php
- src/Helper/Backtrace.php
The phpvfscomposer:// stream wrapper was added to fix a bug in Composer 2.2, which affects all PHP 7.* versions we support. Simple fix is to remove the protocol from the filename, as it is an edge case.
> Fix for phpvfscomposer:// stream wrapper being prefixed to filenames in backtraces

- .github/workflows/laravel.yml
- .github/workflows/lumen.yml
- .github/workflows/quality.yml
- .github/workflows/symfony.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- src/Agent.php
- src/Events/Tag/Tag.php
- src/Extension/RecordedCall.php
- tests/Integration/AgentTest.php
- tests/Integration/TestHelper.php
- tests/Unit/AgentTest.php
- tests/Unit/Extension/RecordedCallTest.php
> Add HTTP span into file_get_contents and curl_exec

- .github/workflows/continuous-integration.yml
Fixes [this issue](https://github.com/scoutapp/scout-apm-php/runs/4850034468?check_suite_focus=true):
```
Run sudo apt-get install -y libcurl4-openssl-dev
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
libpcre3-dev : Depends: libpcre3 (= 2:8.44-2+ubuntu20.04.1+deb.sury.org+1) but 2:8.39-12build1 is to be installed
libpcrecpp0v5 : Depends: libpcre3 (>= 2:8.41) but 2:8.39-12build1 is to be installed
php7.1-cgi : Depends: libpcre3 (>= 2:8.41) but 2:8.39-12build1 is to be installed
php7.1-cli : Depends: libpcre3 (>= 2:8.41) but 2:8.39-12build1 is to be installed
php7.1-fpm : Depends: libpcre3 (>= 2:8.41) but 2:8.39-12build1 is to be installed …
```
> Fix CI failures
