src/Agent.php
src/Connector/CommandWithChildren.php
src/Connector/CommandWithParent.php
src/Events/Request/Request.php
src/Events/Span/Span.php
src/Events/Tag/Tag.php
tests/Integration/AgentTest.php
tests/Unit/Events/Span/SpanTest.php

#47 - fixing order of events

---

composer.json
composer.lock
src/Agent.php
src/Extension/RecordedCall.php
tests/Integration/AgentTest.php
tests/Unit/Extension/RecordedCallTest.php

https://trello.com/c/QV1zmJfi/26-record-arguments-from-logged-calls-eg-url-for-filegetcontents
Also fixes #56

Support arguments from ext

---

src/CoreAgent/AutomaticDownloadAndLaunchManager.php

Always provide --log-file parameter to core-agent

---

src/CoreAgent/AutomaticDownloadAndLaunchManager.php

These were accidentally renamed in the original refactoring.

Fixing formatting of config values for core agent execution

---

src/Events/Request/Request.php
src/Helper/Backtrace.php
tests/Unit/Helper/BacktraceTest.php

#61 - Improvements to backtrace

---

.travis.yml
README.md

Install scoutapm using PECL instead of self-compiling

---

CHANGELOG.md
src/Logger/FilteredLogLevelDecorator.php
tests/Unit/Logger/FilteredLogLevelDecoratorTest.php

Add a clearer exception description for invalid log level

---

.travis.yml
README.md

Removed -alpha stability flag from pecl install docs and build

---

CHANGELOG.md
src/Events/Metadata.php
tests/Unit/Events/MetadataTest.php

Added language_version key to be sent with metadata

---

CHANGELOG.md
src/Config.php
src/Config/Source/DerivedSource.php
src/Helper/LibcDetection.php
tests/Unit/Config/Source/DerivedSourceTest.php
tests/Unit/Helper/LibcDetectionTest.php

Added detection of /etc/alpine-release to determine if musl is used

---

tests/Integration/AgentTest.php

Explicit comment about intentionally different env var name

---

src/Agent.php
tests/Unit/AgentTest.php

Tidied up the test a little too.

Reset request after send

---

src/Config/Source/DefaultSource.php

Increased core version to 1.2.7

---

src/Agent.php
src/Connector/Exception/FailedToSendCommand.php
src/Connector/SocketConnector.php
tests/Unit/AgentTest.php

Check empty string socket read & only Register once

---

src/Agent.php
src/Connector/SocketConnector.php
tests/Integration/AgentTest.php

Do not preemptively try to connect if monitoring is disabled

---

src/Agent.php
src/Events/Metadata.php
src/Extension/ExtentionCapabilities.php
src/Extension/PotentiallyAvailableExtensionCapabilities.php
src/Extension/Version.php
tests/Integration/AgentTest.php
tests/Integration/TestHelper.php
tests/Unit/AgentTest.php
tests/Unit/Events/MetadataTest.php
tests/Unit/Extension/PotentiallyAvailableExtensionCapabilitiesTest.php
tests/Unit/Extension/VersionTest.php

Check extension version is recent

---

src/Agent.php
src/Config.php
src/Config/ConfigKey.php
src/Config/Source/DefaultSource.php
tests/Unit/AgentTest.php

This should help us debug cases such as #171

Added option to add payload content to debug logs

---

.github/workflows/build.yml
composer.json
composer.lock
src/CoreAgent/Downloader.php
src/CoreAgent/Manifest.php
src/Events/Metadata.php
src/Helper/Backtrace.php
src/Helper/Timer.php
tests/Unit/AgentTest.php
tests/Unit/Events/MetadataTest.php
tests/Unit/Helper/TimerTest.php

Fixes libraries in metadata serialisation

---

src/Agent.php
src/Events/Metadata.php
src/Events/Span/Span.php
src/Helper/Backtrace.php
src/Helper/LocateFileOrFolder.php
tests/Unit/Events/MetadataTest.php
tests/Unit/Helper/BacktraceTest.php
tests/Unit/Helper/LocateFileOrFolderTest.php

Filter vendor/ contents from backtraces

---

src/Agent.php
tests/Unit/AgentTest.php

Add TTL for metadata caching

---

composer.json
composer.lock
src/Events/Metadata.php
tests/Integration/AgentTest.php
tests/Unit/Events/MetadataTest.php

Use composer-plugin-api v2 for library versions in metadata

---

Makefile
known-issues.xml
phpcs.xml.dist
psalm.xml.dist
src/Events/Metadata.php
src/Helper/ComposerPackagesCheck.php
src/Logger/FilteredLogLevelDecorator.php
tests/Unit/Events/MetadataTest.php
tests/Unit/Logger/FilteredLogLevelDecoratorTest.php
tests/psalm-stubs.php

Supersedes #216
Contribution from @pjohnmeyer (with CI fixes added)

Log invalid log levels, then default to 'debug'

---

.github/workflows/laravel.yml
.github/workflows/lumen.yml
CHANGELOG.md
README.md
src/Config.php
src/Config/Source/DefaultSource.php
src/Logger/FilteredLogLevelDecorator.php
tests/Unit/AgentTest.php
tests/Unit/Logger/FilteredLogLevelDecoratorTest.php

Increase default log level to warning

---

CHANGELOG.md
src/Agent.php
src/Events/Request/Request.php
src/Events/Span/Span.php
src/Laravel/Database/QueryListener.php
src/ScoutApmAgent.php
src/ScoutApmBundle/EventListener/DoctrineSqlLogger.php
tests/Integration/AgentTest.php

Prevent double-logging of SQL queries

---

.github/workflows/quality.yml
CHANGELOG.md
src/Config/Source/DefaultSource.php

Updated Core Agent version to 1.4.0
